### PR TITLE
Django 3.0 compatibility

### PR DESCRIPTION
**Pull request by nijel**
I've fixed compatibility with Django 3.0 and updated test environment to test current Python versions.

### CODE REVIEW

**Comment by codingjoe** [comment]
@nijel thanks for contribution. Much appreciated. Actually, since you are already removing support for old Django version, please also remove support for Python 3 and the six dependency.
Speaking of, you can also remove Django 1.11 (almost EoL) and add 2.2.
Thanks for the effort, I really appreciate it!

**Comment by codingjoe** [comment]
I'll release a new major version once this is merged.

**Comment by nijel** [comment]
Okay, I didn't want to be that intrusive :-).

**Comment by nijel** [comment]
Done

**Comment by codingjoe** [comment]
Thanks! Released in [5.0.0](https://github.com/codingjoe/django-vies/releases/tag/5.0.0) 🎉

**Pull request merged**
