### PR TITLE
Allow for one more type of IE vat numbers

### LINKED ISSUE #20: Error in IE validation
The current validation for IE VAT numbers does not accept this format: IE1234567XX

For instance IE3286438VH is not accepted, even though it's a valid VAT number.
See https://www.gov.uk/guidance/vat-eu-country-codes-vat-numbers-and-vat-in-other-languages

### PR DESCRIPTION
**Pull request by chripede**
Fix #20

### CODE REVIEW

**Comment by codingjoe** [comment]
@chripede please fix the pep8 error. Don't worry about the pep257 errors.

**Comment by chripede** [comment]
Should be fixed now

**Comment by codingjoe** [comment]
@chripede can you please rebase and squash your commits?

**Comment by chripede** [comment]
@codingjoe rebased into one commit

**Comment by codingjoe** [comment]
@chripede please fix the pep8 naming error. I'll merge it then including your translation and release.

**Comment by codingjoe** [comment]
I did it for you.

**Comment by chripede** [comment]
:+1: thanks

**Pull request merged**
